In [3]:
import numpy as np
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [4]:
path = 'iris_train.data'
with open(path, 'r') as f:
    train_data_ = f.readlines()

In [5]:
type(train_data_)

list

In [6]:
train_data_ [0]

'5.7,2.9,4.2,1.3,Iris-versicolor\n'

In [7]:
path = 'iris_validation.data'
with open(path, 'r') as f:
    val_data_ = f.readlines()

In [8]:
path = 'iris_test.data'
with open(path, 'r') as f:
    test_data_ = f.readlines()

In [9]:
print(len(train_data_),len(val_data_),len(test_data_))

90 30 30


In [10]:
train_x, train_y, val_x, val_y, test_x, test_y = [], [], [], [], [], [] 

In [11]:
for i in train_data_:
    i = i.split(',')
    train_x.append([eval(j) for j in i[:4]])
    train_y.append(i[-1].strip())

In [12]:
train_x[:5]

[[5.7, 2.9, 4.2, 1.3],
 [5.5, 3.5, 1.3, 0.2],
 [5.8, 2.7, 5.1, 1.9],
 [4.5, 2.3, 1.3, 0.3],
 [6.1, 3.0, 4.9, 1.8]]

In [13]:
for i in val_data_:
    i = i.split(',')
    val_x.append([eval(j) for j in i[:4]])
    val_y.append(i[-1].strip())

In [14]:
for i in test_data_:
    i = i.split(',')
    test_x.append([eval(j) for j in i[:4]])
    test_y.append(i[-1].strip())

In [15]:
test_y[:5]

['Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa']

In [16]:
le = LabelEncoder()
train_y_ = le.fit_transform(train_y)

In [17]:
train_y_[:5]

array([1, 0, 2, 0, 2], dtype=int64)

In [18]:
val_y_ = le.transform(val_y)

In [19]:
val_y_[:5]

array([0, 2, 0, 1, 1], dtype=int64)

In [20]:
test_y_ = le.transform(test_y)

In [21]:
test_y[:5]

['Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa']

In [22]:
train_x = np.array(train_x)

In [23]:
train_x.shape

(90, 4)

In [24]:
train_y_ = np.array(train_y_)

In [25]:
train_y_.shape

(90,)

In [26]:
val_x, val_y, test_x, test_y = np.array(val_x), np.array(val_y_), np.array(test_x), np.array(test_y_)

In [27]:
type(val_x)


numpy.ndarray

In [28]:
val_x.shape

(30, 4)

In [144]:
model = SVC(kernel='linear', C=0.05)

In [145]:
model.fit(train_x,train_y_)

SVC(C=0.05, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [146]:
val_pred = model.predict(val_x)

In [147]:
val_pred

array([0, 2, 0, 1, 1, 1, 2, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1, 0, 2, 0, 0, 2,
       2, 2, 1, 0, 2, 0, 1, 2], dtype=int64)

In [148]:
val_y_

array([0, 2, 0, 1, 1, 1, 1, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1, 0, 1, 0, 0, 2,
       2, 2, 1, 0, 2, 0, 2, 2], dtype=int64)

In [149]:
accuracy_score(val_y_, val_pred)

0.9

In [150]:
test_pred = model.predict(test_x)

In [151]:
test_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [152]:
test_y_

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [153]:
accuracy_score(test_y_, test_pred)

1.0